### ISSUE TITLE
[WebGL2] An error occurred when testing reshape using special value -1 with WebGL2 backend

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#110]
**Test Env:**
Chromium Version : nightly build 65.0.3324.0 (revision 81edd55)
OS : Mac OS
webml-polyfill: commit [5ea28b2](https://github.com/intel/webml-polyfill/commit/5ea28b2171cef11eabf052384ac8e6d5ec570cde)

**Expected Result:**
No error occurs.

**Actual Result:**
```
Error: Invalid value 0,0,0,0
    at Execution.setOutput (https://brucedai.github.io/nt/dist/webml-polyfill.js:7935:15)
    at r.<anonymous> (operations/reshape_neg1.js:32:17)
```

**How to reproduce:**
1. Launch chromium and disable WebML flag
2. Access to https://brucedai.github.io/nt/test/reshape_neg1.html?backend=webgl2

**Comment by Wenzhao-Xiang** [comment]
The test case set the outputShape with [2,-1], but this will lead to the operation of the error detection mechanism.It's contradictory. Since it's not so good to operate the shape in `Execution.setOutput`,I consider to mask error detection mechanism when value '-1' occurs,or value '-1' is not supported in this version.

**Comment by Wenzhao-Xiang** [comment]
@huningxin It seems we use shape with '-1'  only in ops "reshape",right?
So could I do like above?

**Comment by Wenzhao-Xiang** [comment]
This issue due to 
[https://github.com/intel/webml-polyfill/blob/master/src/nn/Execution.js#L67](url)
`if (!model._validateOperandValue(buffer, operand)) {`
  `throw new Error(Invalid value ${buffer});`
   ` }`
[https://github.com/intel/webml-polyfill/blob/master/src/nn/Model.js#L192](url)
`if (valueLength != neededLength) {`
        `console.error(Sets ${valueLength} bytes when needing ${neededLength});`
       ` return false;`
'-1' means this dimension should be calculated in ops "reshape",but here throw error before it.
The framework needs to calculate all shapes in advance. Is the test case necessary?
@huningxin

**Comment by huningxin** [comment]
@BruceDai , could you please explain why this test case expects no error throws?

**Comment by BruceDai** [comment]
@huningxin I designed this case referring to [tf.manip.reshape of tensorflow](https://www.tensorflow.org/api_docs/python/tf/manip/reshape) and [numpy.reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html#numpy.reshape) which both use the unspecified value -1. 
So would we also support it ?

**Comment by huningxin** [comment]
I don't think we support tf or numpy. Currently, the API design is based on NN API. I am not aware RESHAPE of NN API supports that. If that is the case, please update the test case accordingly.
