### ISSUE TITLE
[WASM] TypeError occurred when testing reshape using special value -1 with WASM backend

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#119]
**Test Env:**
Chromium Version : nightly build 67.0.3503.0 (revision 3dd7088)
OS : Mac OS
webml-polyfill: commit [e4b1188](https://github.com/intel/webml-polyfill/commit/e4b11886f7b9b42b6525818172fb6f26d0497ed1)

**Expected Result:**
Test should pass.

**Actual Result:**
```
TypeError: Passing a number "-1" from JS side to C/C++ side to an argument of type "unsigned int", which is outside the valid range [0, 4294967295]!
    at Object.toWireType (https://brucedai.github.io/nt/dist/webml-polyfill.js:10819:17)
    at __emval_as (https://brucedai.github.io/nt/dist/webml-polyfill.js:10895:220)
    at wasm-function[61]:163
    at wasm-function[60]:41
    at wasm-function[92]:43
    at wasm-function[727]:16
    at dynCall_viii_2 (eval at makeDynCaller (https://brucedai.github.io/nt/dist/webml-polyfill.js:10558:251), <anonymous>:4:12)
    at Shape.desc.set [as dimensions] (https://brucedai.github.io/nt/dist/webml-polyfill.js:10707:97)
    at PreparedModel._allocateShape (https://brucedai.github.io/nt/dist/webml-polyfill.js:6707:24)
    at PreparedModel._callee$ (https://brucedai.github.io/nt/dist/webml-polyfill.js:6243:49)
```
**How to Reproduce:**
1. Launch chromium and disable WebML flag
2. Access to https://brucedai.github.io/nt/test/reshape_neg1.html?backend=wasm

**Comment by Christywl** [comment]
Close this issue since the test case with special value -1 has been removed.
