### ISSUE TITLE
[WASM] An error occurred when testing concatenation using axis being -1 with WASM backend 

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#120]
**Test Env:**
Chromium Version : nightly build 67.0.3503.0 (revision 3dd7088)
OS : Mac OS
webml-polyfill: commit [e4b1188](https://github.com/intel/webml-polyfill/commit/e4b11886f7b9b42b6525818172fb6f26d0497ed1)

**Expected Result:**
Test should pass.

**Actual Result:**
```
Error: concatenationPrepare fails
    at PreparedModel._executeOperation (https://brucedai.github.io/nt/dist/webml-polyfill.js:6644:21)
    at https://brucedai.github.io/nt/dist/webml-polyfill.js:6299:25
    at Array.forEach (<anonymous>)
    at PreparedModel._callee2$ (https://brucedai.github.io/nt/dist/webml-polyfill.js:6298:34)
    at tryCatch (https://brucedai.github.io/nt/dist/webml-polyfill.js:18431:40)
    at Generator.invoke [as _invoke] (https://brucedai.github.io/nt/dist/webml-polyfill.js:18669:22)
    at Generator.prototype.(anonymous function) [as next] (https://brucedai.github.io/nt/dist/webml-polyfill.js:18483:21)
    at step (https://brucedai.github.io/nt/dist/webml-polyfill.js:6199:191)
    at https://brucedai.github.io/nt/dist/webml-polyfill.js:6199:437
    at new Promise (<anonymous>)
```
**How to Reproduce:**
1. Launch chromium and disable WebML flag
2. Access to https://brucedai.github.io/nt/test/concatenation_neg1.html?backend=wasm

**Comment by Christywl** [comment]
Close this issue since the test case with special value -1 has been removed.
