### ISSUE TITLE
[Question] Semantic segmentation example is failing with backend as WEBNN

### ISSUE THREAD

**Issue by anand-371** [intel/webml-polyfill#1397]
Hi,
1.i have built chromium for WebNN support.
2.currently running openvino 2020.3.355

Operating System: Ubuntu 20.04.2 LTS

Issue:
I have executed build with  the command /usr/bin/chromium-browser-unstable --no-sandbox.
When i try running the image classification task with 
Backend=FAST_SINGLE_ANSWER,Model=MobileNet v1,sucessfully predicts 
Backend=FAST_SINGLE_ANSWER,Model=MobileNet v1 Quant,Prediction failed with message(finishfails:5)
Backend=FAST_SINGLE_ANSWER,Model=MobileNet v2,sucessfully predicts.
Backend=FAST_SINGLE_ANSWER,Model=MobileNet v2 Quant,Prediction failed with message(finishfails:5)
Backend=FAST_SINGLE_ANSWER,Model=SqueezaNet,sucessfully predicts.

Similarly for person detection 
Backend=FAST_SINGLE_ANSWER,Model=SSD MobileNet v1,sucessfully predicts 
Backend=FAST_SINGLE_ANSWER,Model=SSD MobileNet v1,Prediction failed with message(finishfails:5) 
thus working for few models and failing for a few.

However under Semantic segmentation example with WebNN(FAST_SINGLE_ANSWER) as backend none
of the models seems to be successfully predicting.
below mentioned are the terminal logs when the backend was selected as FAST_SINGLE_ANSWER with various models selected for semantic segmentation example.

[182064:182064:0602/163154.308376:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[182064:182247:0602/163235.435756:ERROR:compilation_delegate_dnnl.cc(174)] Operation type 39 is not supported.
[182064:182247:0602/163236.399590:ERROR:compilation_delegate_dnnl.cc(174)] Operation type 39 is not supported.
[182064:182247:0602/163241.891908:ERROR:compilation_delegate_dnnl.cc(174)] Operation type 39 is not supported.
[182064:182247:0602/163246.315614:ERROR:compilation_delegate_dnnl.cc(174)] Operation type 39 is not supported.
[182064:182247:0602/163252.399258:ERROR:compilation_delegate_dnnl.cc(632)] Operation type 18 is not supported.
[182064:182247:0602/163303.435654:ERROR:compilation_delegate_dnnl.cc(174)] Operation type 39 is not supported.
[182064:182247:0602/163305.561404:ERROR:compilation_delegate_cl_dnn.cc(156)] [clDNN] failed to create cldnn ocl engine -1 clGetPlatformIDs error -1001
[182064:182247:0602/163308.322920:ERROR:compilation_delegate_cl_dnn.cc(156)] [clDNN] failed to create cldnn ocl engine -1 clGetPlatformIDs error -1001

How do I go about in resolving this issue? are there any dependencies which i have not missed out?

**Comment by mingmingtasd** [comment]
Hi, please refer to https://github.com/intel/webml-polyfill/wiki/How-to-Run-Chromium-builds-with-WebNN-API, and try `/usr/bin/chromium-browser-unstable --no-sandbox --use-inference-engine` for Linux with Inference Engine backends. Thanks! @anand-371

**Comment by anand-371** [comment]
Hey, So i had tried that before but nevertheless i reinstalled it.
i am currently running 
Open cv: 4.5.2-openvino
python: 3.8.5
i downloaded the openvino toolkit 2021.3.394 and installed it.
The verification scripts for demo security barrier camera runs successfully whereas the ./demo_squeezenet_download_convert_run.sh fails with the following error.

========== Retrieving /home/test/openvino_models/models/public/squeezenet1.1/squeezenet1.1.prototxt from the cache

========== Downloading /home/test/openvino_models/models/public/squeezenet1.1/squeezenet1.1.caffemodel
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /forresti/SqueezeNet/raw/a47b6f13d30985279789d08053d37013d67d131b/SqueezeNet_v1.1/squeezenet_v1.1.caffemodel (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/downloader/downloader.py", line 82, in try_download
    chunk_iterable, continue_offset = start_download(offset=progress.size)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/tools/downloader/common.py", line 355, in start_download
    response = session.get(self.url, stream=True, timeout=DOWNLOAD_TIMEOUT,
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /forresti/SqueezeNet/raw/a47b6f13d30985279789d08053d37013d67d131b/SqueezeNet_v1.1/squeezenet_v1.1.caffemodel (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1123)')))
########## Error: Download failed

FAILED:
squeezenet1.1
Error on or near line 159; exiting with status 1

when i try running  try /usr/bin/chromium-browser-unstable --no-sandbox --use-inference-engine
and run the sematic segmentation or any other example with the backend as (FAST_SINGLE_ANSWER/SUSTAINED_SPEED/Low power)i get an error "Neural Network service unavailable".
Any suggestions on how to go about?

**Comment by mingmingtasd** [comment]
Please ignore downloading errors because `security barrier camera runs successfully` can prove that your openvino has been installed correctly. Please paste more error log here after doing `/usr/bin/chromium-browser-unstable --no-sandbox --use-inference-engine` and running examples so that I can find the root cause for you. Thanks! @anand-371

**Comment by anand-371** [comment]
yes sure!
so when i run the command  /usr/bin/chromium-browser-unstable --no-sandbox --use-inference-engine 
and try any of the examples it shows me 'Prediction failed','neural network service unavailable '.
However the errors don't seem to be logging as i choose different models with back end as Webnn(FAST_SINGLE_ANSWER/SUSTAINED_SPEED/LOW_POWER).



The following is the error log on my terminal:
[234038:234038:0604/095143.132059:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[234038:234176:0604/095149.343424:ERROR:late_binding_symbol_table.cc(69)] Can't load libie_nn_c_api.so : /opt/chromium.org/chromium-unstable/libie_nn_c_api.so: undefined symbol: _ZN6ngraph7element3f32E
Received signal 11 SEGV_MAPERR 000000000000
#0 0x559a57264689 (/opt/chromium.org/chromium-unstable/chrome+0x59d7688)
#1 0x559a571de833 (/opt/chromium.org/chromium-unstable/chrome+0x5951832)
#2 0x559a57264225 (/opt/chromium.org/chromium-unstable/chrome+0x59d7224)
#3 0x7f2a337843c0 (/usr/lib/x86_64-linux-gnu/libpthread-2.31.so+0x153bf)
  r8: 0000000000000000  r9: 0000000000000000 r10: 00000b60925dbf70 r11: 0000000000000000
 r12: 00007f2a1466bce0 r13: 00000b6091f62640 r14: 00007f2a1466bc88 r15: 00000b6091286a00
  di: 00000b6091286a78  si: 00000b6091f4fba0  bp: 00007f2a1466bc20  bx: 00007f2a1466bab8
  dx: 00000b6091f4fba0  ax: 00000b609128ae10  cx: 00000b6091f4fba8  sp: 00007f2a1466ba68
  ip: 0000000000000000 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000014
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[234177:234177:0604/095149.467322:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.

**Comment by mingmingtasd** [comment]
How did you `built chromium for WebNN support`, which doc did you refer to? @anand-371

**Comment by mingmingtasd** [comment]
> How did you `built chromium for WebNN support`, which doc did you refer to? @anand-371
Note that:

1.  Install openvino 2021 version and set OpenVINO environment by execute /opt/intel/openvino_2021/bin/setupvars.sh
2.  Execute ./third_party/ienn/build_ienn_unix.sh
3. Then ninja and re-install chromium build again.
@anand-371

**Comment by anand-371** [comment]
i have followed this document for building chromium for WebNN support.
https://github.com/intel/webml-polyfill/wiki/How-to-build-chromium-on-Linux

> > How did you `built chromium for WebNN support`, which doc did you refer to? @anand-371
> > Note that:
> 
> 1. Install openvino 2021 version and set OpenVINO environment by execute /opt/intel/openvino_2021/bin/setupvars.sh
> 2. Execute ./third_party/ienn/build_ienn_unix.sh
> 3. Then ninja and re-install chromium build again.
>    @anand-371

i have followed these steps mentioned but the same error persists. running the examples  shows me 'Prediction failed',            
 'neural network service unavailable ' on the chromium browser.

**Comment by mingmingtasd** [comment]
1. Install openvino 2021 version and set OpenVINO environment by execute /opt/intel/openvino_2021/bin/setupvars.sh
 2. Execute ./third_party/ienn/build_ienn_unix.sh
 3. **cp ./third_party/ienn/build/intel64/Release/lib/libie_nn_c_api.so ./out/Default/**
 4. **rm out/Default/chromium-browser-unstable_*.deb**
 4. autoninja -C out/Default chrome chrome unstable_deb
 5. out/Default/chrome-wrapper --no-sandbox --use-inference-engine
 or :
sudo dpkg -r chromium-browser-unstable
sudo dpkg -i out/Default/chromium-browser-unstable_*.deb
/usr/bin/chromium-browser-unstable --no-sandbox --use-inference-engine
 @anand-371 Please follow steps above, pay attention to step 3,4. I have verified that it can work correctly.

**Comment by anand-371** [comment]
Hey,
Thanks a lot, @mingmingtasd  
This seemed to have solved the issue.

> 1. Install openvino 2021 version and set OpenVINO environment by execute /opt/intel/openvino_2021/bin/setupvars.sh
> 2. Execute ./third_party/ienn/build_ienn_unix.sh
> 3. **cp ./third_party/ienn/build/intel64/Release/lib/libie_nn_c_api.so ./out/Default/**
> 4. **rm out/Default/chromium-browser-unstable_*.deb**
> 5. autoninja -C out/Default chrome chrome unstable_deb
> 6. out/Default/chrome-wrapper --no-sandbox --use-inference-engine
>    or :
>    sudo dpkg -r chromium-browser-unstable
>    sudo dpkg -i out/Default/chromium-browser-unstable_*.deb
>    /usr/bin/chromium-browser-unstable --no-sandbox --use-inference-engine
>    @anand-371 Please follow steps above, pay attention to step 3,4. I have verified that it can work correctly.
