### ISSUE TITLE
[test] regression checker fails on Windows

### ISSUE THREAD

**Issue by huningxin** [intel/webml-polyfill#530]
The regression checker continues to fail on my Windows environment. The error log is:
```
> RegressionChecker@0.0.1 start C:\Users\mltest\code\webml-polyfill\test\tools\RegressionChecker
> node ./src/main.js

RC -- checking runtime environment....
RC -- runtime environment: Windows
RC -- chromium to be tested is installed correctly
RC -- checking chromium code is start

DevTools listening on ws://127.0.0.1:51825/devtools/browser/0d8a13a2-06e9-417e-b114-e8f4cb4c2881
RC -- open remote URL: https://brucedai.github.io/nt/test/index-local.html?backend=cldnn
RC -- Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:58088
(node:1556) UnhandledPromiseRejectionWarning: Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:58088
    at ClientRequest.<anonymous> (C:\Users\mltest\code\webml-polyfill\test\tools\RegressionChecker\node_modules\selenium-webdriver\http\index.js:244:15)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:1556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Did I miss anything?

**Comment by huningxin** [comment]
Use TcpView, it looks like our tool opens too many local port as the screenshot

![image](https://user-images.githubusercontent.com/1005673/51881919-f4873600-23b7-11e9-8635-f831d5089967.png)

**Comment by cuiyanx** [comment]
This issue look like webdriver's bug, such as [#4162](https://github.com/SeleniumHQ/selenium/issues/4162) and [#5758](https://github.com/SeleniumHQ/selenium/issues/5758). 
I try to fix it.

**Comment by cuiyanx** [comment]
Or another way to fix it: [System.Net.SocketException - Only one usage of each socket address (protocol/network address/port) is normally permitted](https://github.com/hieucd04/Helix/issues/1)

**Comment by huningxin** [comment]
@BruceDai , or could you please give me some manual steps to do the regression check? Thanks!

**Comment by BruceDai** [comment]
@huningxin Sorry for this inconvenient user experience.  For this case, please open target chromium browser and type these url and check results manually, thanks.
https://brucedai.github.io/nt/test/index-local.html?backend=cldnn
https://brucedai.github.io/nt/test/index-local.html?backend=mkldnn
https://brucedai.github.io/nt/test/index-local.html?backend=wasm
https://brucedai.github.io/nt/test/index-local.html?backend=webgl

Please refer to baseline summary infromation of #Line 72 to #Line 95 of [RegressionChecker/baseline/baseline.config.json](https://github.com/intel/webml-polyfill/blob/master/test/tools/RegressionChecker/baseline/baseline.config.json#L72)

**Comment by huningxin** [comment]
Thanks @BruceDai  and @cuiyanx .

I tried 

> @huningxin follow this:
> [System.Net.SocketException - Only one usage of each socket address (protocol/network address/port) is normally permitted](https://github.com/hieucd04/Helix/issues/1)

It works for me. Cheers!

**Comment by huningxin** [comment]
remove P1 and Jan tag as we have a workaround.

**Comment by cuiyanx** [comment]
This issue will be fixed with #912 .
