### ISSUE TITLE
[WebGL2] 4D dimensions shapes are not supported

### ISSUE THREAD

**Issue by Christywl** [intel/webml-polyfill#95]
**Test Env:**
Chromium Version : nightly build 65.0.3324.0 (revision 81edd55)
OS : Mac OS
webml-polyfill: commit [ee18609](https://github.com/intel/webml-polyfill/commit/ee18609f980abe735f88e0547a9240c3b2f98ba7)

**Expected Result:**
Support the 4D shapes

**Actual Result:**
Some shapes are not supported:
```
Error: the shape 5,52,60,3 is not supported
    at https://brucedai.github.io/nt/dist/webml-polyfill.js:8095:21
    at Array.forEach (<anonymous>)
    at https://brucedai.github.io/nt/dist/webml-polyfill.js:8086:24
    at new Promise (<anonymous>)
    at Model.execute (https://brucedai.github.io/nt/dist/webml-polyfill.js:8078:14)
    at Execution._callee$ (https://brucedai.github.io/nt/dist/webml-polyfill.js:7961:44)
    at tryCatch (https://brucedai.github.io/nt/dist/webml-polyfill.js:18425:40)
    at Generator.invoke [as _invoke] (https://brucedai.github.io/nt/dist/webml-polyfill.js:18663:22)
    at Generator.prototype.(anonymous function) [as next] (https://brucedai.github.io/nt/dist/webml-polyfill.js:18477:21)
    at step (https://brucedai.github.io/nt/dist/webml-polyfill.js:7859:191)
```
`Error: the shape 5,50,70,3 is not `
`Error: the shape 2,2,2,2 is not supported` 
**How to reproduce:**
1. Launch chromium and disable the WebML
2. Run tests:

- Access to https://brucedai.github.io/nt/test/cts-all.html?backend=webgl2

   - check result for Avg pool float example/2	
   - check result for Avg pool float example/4		
   - check result for Max pool float example/2	
   - check result for Max pool float example/3	

- Access:
https://brucedai.github.io/nt/test/concatenation.html?backend=webgl2
https://brucedai.github.io/nt/test/concatenation_3.html?backend=webgl2
https://brucedai.github.io/nt/test/concatenation_neg1.html?backend=webgl2

**Comment by Christywl** [comment]
Found this:
https://github.com/intel/webml-polyfill/blob/master/src/nn/webgl2/Model.js#L68:
```
 let shape = nnOperands[inputIndex].dimensions;
 if (shape.length === 4 && shape[0] === 1) {
   shape = shape.slice(1,4);
 } else if (shape.length === 3) {
   shape = shape;
 } else {
   throw new Error(`the shape ${shape} is not supported`);
 }
```
